### ISSUE TITLE
std::uncaught_exception() becomes negative

### ISSUE THREAD

**Issue by rkaminsk** [pathscale/libcxxrt#49] opened 2017-09-27 21:45 UTC
Hi, I am using clang + libcxx + libcxxrt and the following program fails:
```cpp
#include <stdexcept>
#include <iostream>
#include <cassert>

int main() {
    try {
        throw std::runtime_error("test");
    }
    catch (...) {
        try {
            throw;
        }
        catch (...) {
        }
    }
    std::cerr << "uncaught exceptions: " << std::uncaught_exceptions() << std::endl;
    assert (!std::uncaught_exception());
}
```

Interestingly, replacing 'throw;' with `std::rethrow_exception(std::current_exception());` worksaround the problem. When using libcxxabi or libsupc++ instead, the program works as expected.

**Comment by horenmar** [comment] 2017-09-28 07:51
Basically a duplicate of #45

**Closed** 2017-09-28 09:22 UTC
